/*******************************************************************************
Progetto       : dBsee 4.3
Descrizione    : Funzioni di utilita'
Programmatore  : Baccan Matteo
*******************************************************************************/
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
FUNCTION dfLockList()
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
LOCAL aRecno

IF dfAsDriver( RDDNAME() )
   aRecno := {}
ELSE
   #IFDEF __XPP__
   aRecno := DBRLOCKLIST_XPP()
   #ELSE
   aRecno := DBRLOCKLIST()
   #ENDIF
ENDIF

RETURN aRecno
