//*****************************************************************************
//Progetto       : Generato dBsee 4.0
//Descrizione    : Inizializzazione dfUsr
//Programmatore  : Baccan Matteo
//*****************************************************************************
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
FUNCTION dfArrUsr()
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
STATIC aUsr := {  49 ,;  // USR_TOP
                   0 ,;  // USR_LEFT
                  79 ,;  // USR_RIGHT
                 "³" ,;  // USR_SEPACT
                 "³" ,;  // USR_SEPINV
                  "" ,;  // USR_MSG
                  "" ,;  // USR_ICON
                  ""  }  // USR_STATE
RETURN aUsr
