/******************************************************************************
Progetto       : dBsee 4.0
Descrizione    : Funzioni di utilita'
Programmatore  : Baccan Matteo
******************************************************************************/
#include "Common.ch"
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
PROCEDURE tbShrink( oTbr ) //
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
LOCAL oCol := oTbr:GetColumn(oTbr:ColPos)
DEFAULT oCol:Width TO tbColWidth( oTbr, oCol )
IF oCol:Width>1
   oCol:Width--
   tbConfigure(oTbr)
   tbStab(oTbr,.T.)
ENDIF
RETURN
