/******************************************************************************
 Progetto       : Esempio Crystal Report
 Sottoprogetto  : Esempio Crystal Report
 Programma      : C:\PROGRA~1\VISUAL~1\SAMPLES\CRYSTAL\source\_Menu.prg
 Template       : C:\Programmi\VisualdBsee\bin\..\tmp\xbase\initprg.tmp
 Descrizione    : Menu applicazione
 Programmatore  :
 Data           : 12-10-04
 Ora            : 16.02.59
******************************************************************************/

FUNCTION Main(cPar1, cPar2, cPar3, cPar4, cPar5, cPar6, cPar7)
   MenuExe(cPar1, cPar2, cPar3, cPar4, cPar5, cPar6, cPar7)
RETURN NIL

