/* ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³                                                                      ³
   ³           2000 - 2004 by Albalog Srl - Florence - Italy              ³
   ³                                                                      ³
   ³                         Visual dBsee TOOLBAR                         ³
   ³                                                                      ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ */

#ifndef __VDB_TOOLBAR_CH__
   #define __VDB_TOOLBAR_CH__

   #Define TB_BUTTON 1
   #Define TB_TEXT 2
   #Define TB_ICON 3
   #Define TB_START 4
   #Define TB_SEPARATOR 5
   #Define TB_EVENT 6
   #Define TB_SETUP 7
   #Define TB_ICONTXT 8
   #Define TB_COMBO 9

   #Define TBD_ICON_ICON 1
   #Define TBD_ICON_TEXT 2

   #Define TBD_OBJ 1
   #Define TBD_SHADOW 2
   #Define TBD_TIP 3

   #Define xbeM_Idle 1048626

   #Define SL_SEPARATOR 0
   #Define SL_TEXT 1
   #Define SL_ICON 2
   #Define SL_BITMAP 3

   #Define SL_AUTO 0
   #Define SL_MAXSIZE -1

#endif 